name: bigdata-spark-node1

services:
  spark-master:
    image: spark:4.0.1-python3
    container_name: spark-master
    network_mode: host
    command:
      - /bin/bash
      - -lc
      - |
        /opt/spark/sbin/start-master.sh \
          --host 100.127.42.127 \
          --port 7077 \
          --webui-port 8080
        tail -f /dev/null
    environment:
      SPARK_MASTER_HOST: "100.127.42.127"
      SPARK_MASTER_PORT: "7077"
      SPARK_MASTER_WEBUI_PORT: "8080"
      SPARK_LOCAL_DIRS: /spark-local
      SPARK_LOG_DIR: /spark-logs
    volumes:
      - ./service/spark-master/local:/spark-local
      - ./service/spark-master/logs:/spark-logs
    restart: unless-stopped

  spark-worker-1:
    image: spark:4.0.1-python3
    container_name: spark-worker-1
    network_mode: host
    depends_on:
      - spark-master
    command:
      - /bin/bash
      - -lc
      - |
        /opt/spark/sbin/start-worker.sh \
          --host 100.127.42.127 \
          --port 7081 \
          --webui-port 8081 \
          -c 12 \
          -m 24G \
          spark://100.127.42.127:7077
        tail -f /dev/null
    environment:
      SPARK_LOCAL_DIRS: /spark-local
      SPARK_LOG_DIR: /spark-logs
    volumes:
      - ./service/spark-worker-1/local:/spark-local
      - ./service/spark-worker-1/logs:/spark-logs
    restart: unless-stopped

  spark-worker-2:
    image: spark:4.0.1-python3
    container_name: spark-worker-2
    network_mode: host
    depends_on:
      - spark-master
    command:
      - /bin/bash
      - -lc
      - |
        /opt/spark/sbin/start-worker.sh \
          --host 100.127.42.127 \
          --port 7082 \
          --webui-port 8082 \
          -c 12 \
          -m 24G \
          spark://100.127.42.127:7077
        tail -f /dev/null
    environment:
      SPARK_LOCAL_DIRS: /spark-local
      SPARK_LOG_DIR: /spark-logs
    volumes:
      - ./service/spark-worker-2/local:/spark-local
      - ./service/spark-worker-2/logs:/spark-logs
    restart: unless-stopped

  spark-worker-3:
    image: spark:4.0.1-python3
    container_name: spark-worker-3
    network_mode: host
    depends_on:
      - spark-master
    command:
      - /bin/bash
      - -lc
      - |
        /opt/spark/sbin/start-worker.sh \
          --host 100.127.42.127 \
          --port 7083 \
          --webui-port 8083 \
          -c 12 \
          -m 24G \
          spark://100.127.42.127:7077
        tail -f /dev/null
    environment:
      SPARK_LOCAL_DIRS: /spark-local
      SPARK_LOG_DIR: /spark-logs
    volumes:
      - ./service/spark-worker-3/local:/spark-local
      - ./service/spark-worker-3/logs:/spark-logs
    restart: unless-stopped

  spark-worker-4:
    image: spark:4.0.1-python3
    container_name: spark-worker-4
    network_mode: host
    depends_on:
      - spark-master
    command:
      - /bin/bash
      - -lc
      - |
        /opt/spark/sbin/start-worker.sh \
          --host 100.127.42.127 \
          --port 7084 \
          --webui-port 8084 \
          -c 12 \
          -m 24G \
          spark://100.127.42.127:7077
        tail -f /dev/null
    environment:
      SPARK_LOCAL_DIRS: /spark-local
      SPARK_LOG_DIR: /spark-logs
    volumes:
      - ./service/spark-worker-4/local:/spark-local
      - ./service/spark-worker-4/logs:/spark-logs
    restart: unless-stopped

  minio1:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio1
    network_mode: host
    extra_hosts:
      - "minio1:100.127.42.127"
      - "minio2:100.113.89.12"
    command:
      - server
      - --address
      - ":9100"
      - --console-address
      - ":9101"
      - http://minio{1...2}:9100/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./service/minio1/data:/data
    restart: unless-stopped
